// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1XxsC8IkInbOQnJ88c45NGBuUV9GwaZA',
    appId: '1:695522404590:web:a92edadbeaeef3a63f6bff',
    messagingSenderId: '695522404590',
    projectId: 'poemportal-2221d',
    authDomain: 'poemportal-2221d.firebaseapp.com',
    databaseURL: 'https://poemportal-2221d-default-rtdb.firebaseio.com',
    storageBucket: 'poemportal-2221d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEzBuJcyJRdr8RW0c-yd0hJ9uuts5KuU',
    appId: '1:695522404590:android:9c1f6edbbc21edf73f6bff',
    messagingSenderId: '695522404590',
    projectId: 'poemportal-2221d',
    databaseURL: 'https://poemportal-2221d-default-rtdb.firebaseio.com',
    storageBucket: 'poemportal-2221d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmAH67FsL2cU0rRKFiVierLzH3mjMhrM',
    appId: '1:695522404590:ios:6789e3ba643e68ad3f6bff',
    messagingSenderId: '695522404590',
    projectId: 'poemportal-2221d',
    databaseURL: 'https://poemportal-2221d-default-rtdb.firebaseio.com',
    storageBucket: 'poemportal-2221d.appspot.com',
    iosBundleId: 'com.PoemPortal.poemportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYmAH67FsL2cU0rRKFiVierLzH3mjMhrM',
    appId: '1:695522404590:ios:6789e3ba643e68ad3f6bff',
    messagingSenderId: '695522404590',
    projectId: 'poemportal-2221d',
    databaseURL: 'https://poemportal-2221d-default-rtdb.firebaseio.com',
    storageBucket: 'poemportal-2221d.appspot.com',
    iosBundleId: 'com.PoemPortal.poemportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1XxsC8IkInbOQnJ88c45NGBuUV9GwaZA',
    appId: '1:695522404590:web:bfe01eec149b6b123f6bff',
    messagingSenderId: '695522404590',
    projectId: 'poemportal-2221d',
    authDomain: 'poemportal-2221d.firebaseapp.com',
    databaseURL: 'https://poemportal-2221d-default-rtdb.firebaseio.com',
    storageBucket: 'poemportal-2221d.appspot.com',
  );
}
